---
- name: Variables Demo
  hosts: g1
  become: yes
  vars:
  myusername: Ruthtam
  
  tasks:
  - name:  update static page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
...   